import { Shop, ShopCategory, ShopStatus } from "@/models/shop";

export const UPCOMING_SHOPS: Shop[] = [
  {
    id: 2,
    displayName: "Sushi&Wine Transformart Bar",
    address: "Svetog Save 8, Beograd 11000, Serbia",
    logo: "transform_art_bar.png",
    ratings: 4.5,
    status: ShopStatus.Upcoming,
    category: ShopCategory.Restraunt,
  },
  {
    id: 3,
    displayName: "6 Slice Pizza",
    address: "L 49B, Jamia Nagar New Delhi, India",
    logo: "6_slice.png",
    status: ShopStatus.Upcoming,
    category: ShopCategory.Restraunt,
    ratings: 4,
  },
  {
    id: 4,
    displayName: "Chozen",
    address:
      "Remetinec 48e, Zagreb,Proizvodnja kakao, čokoladnih i bombonskih proizvoda",
    logo: "chozen.png",
    status: ShopStatus.Upcoming,
    category: ShopCategory.Restraunt,
    ratings: 4.5,
  },
  {
    id: 5,
    displayName: "Nel Fruits",
    address: "Remote",
    ratings: 4,
    logo: "nel_fruits.png",
    status: ShopStatus.Upcoming,
    category: ShopCategory.Groceries,
  },
  {
    id: 6,
    displayName: "High Castle Books",
    address: "Bišćanov put 6, Zagreb",
    ratings: 4,
    logo: "high_castle_book.png",
    status: ShopStatus.Upcoming,
    category: ShopCategory.Groceries,
  },
  {
    id: 7,
    displayName: "If I Can",
    address: "Bišćanov put 6, Zagreb",
    ratings: 4,
    logo: "if_i_can.png",
    status: ShopStatus.Upcoming,
    category: ShopCategory.Restraunt,
  },
  {
    id: 8,
    displayName: "Vape Shop",
    address: "Bišćanov put 6, Zagreb",
    ratings: 4,
    logo: "vape_shop.png",
    status: ShopStatus.Upcoming,
    category: ShopCategory.Restraunt,
  },
];
